### ISSUE TITLE
Stacktrace incorrect in checkout gen_server call

### ISSUE THREAD

**Issue by joshprice** [devinus/poolboy#87]
The stacktrace points to the wrong place if the checkout gen_server call exits because of a non-timeout reason to a named pool.

https://github.com/devinus/poolboy/blob/master/src/poolboy.erl#L52-L60

```
** (exit) exited in: :gen_server.call(Ellexir.Repo.Pool, {:checkout, #Reference<0.0.1.102>, true}, 5000)
    ** (EXIT) no process
    :erlang.send(Ellexir.Repo.Pool, {:"$gen_cast", {:cancel_waiting, #Reference<0.0.1.102>}}, [:noconnect])
    (stdlib) gen_server.erl:416: :gen_server.do_send/2
    (stdlib) gen_server.erl:232: :gen_server.do_cast/2
    (poolboy) src/poolboy.erl:58: :poolboy.checkout/3
    (db_connection) lib/db_connection/poolboy.ex:36: DBConnection.Poolboy.checkout/2
    (db_connection) lib/db_connection.ex:811: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:717: DBConnection.run/3
    (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
```

/cc @fishcakez

**Comment by marinakr** [comment]
Hi, I have same issue
